### ISSUE TITLE
Expose quick start app.yml, app.livecodescript, and .gitignore

### ISSUE THREAD

**Issue by spencerlearning** [trevordevore/levure#10]
It looks like the quick start app.yml, app.livecodescript, and .gitignore files are embedded as custom properties in the project creator stack. These files should be exposed in the repo for viewing and modifying.

This relates to #8 and #9 .

**Comment by trevordevore** [comment]
Done. I've added the stack script and custom property values to a subfolder in the utils folder. Whenever you save the stack the files in that folder are sucked up and applied to the stack.
