### ISSUE TITLE
logger enhancements

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#101]
I'd like to add another category to logger, specifically for errors as their own class.  Then helpers like the error helper I'm playing with (or the one you currently have packaged with Levure) could use logger to report or store errors.
Another option might be to make logger extensible and get rid of the hard-plumbed classes, but that seems like overkill.

**Comment by trevordevore** [comment]
I would suggest a PR that adds to the hard coded list. I don't think it is worth the extra effort (yet).

Levure doesn't currently ship with an error helper.

**Comment by macMikey** [comment]
Also going to add "all" to future-proof the logger.

**Comment by macMikey** [comment]
For posterity, I'm including the bullets of the offline discussion:
• Log type (developer, network, extensions, etc.) should be added to each entry in the log
• Delimiter(s) or output file type/format type specified by developer
• Escape the message properly so it does not interfere with the delimiters
• Option to include or omit the log type?
• Mark contents of the log-type column for easy searching/filtering?  For example, [extensions] or |extensions|?  I suppose one could also specify left and right "bracket" characters.  Is that too much?

**Comment by macMikey** [comment]
PR 116
