### ISSUE TITLE
Mechanism For Helpers To Self-Set Properties

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#103]
There isn't an (official) mechanism for helpers to automagically use app.yml settings to set their properties.  The only (official) way is to have the main app call a setter.  For example the logger's target and log level have to be set via a setter, instead of being able to read the appropriate values from app.yml and do it itself.

**Comment by trevordevore** [comment]
I may not b le understanding what you are trying to do, but why can’t the logger library use the levureAppGet and levureAppSet?

The helpers wiki page has this example:

if levureAppHasProperty("app updater") then
    put levureAppGet("app updater") into tConfigA
    _replaceVariables xFiledata, pBuildProfile, tConfigA
  end if

**Comment by macMikey** [comment]
Uhhhhhhhhhhh how did I miss that?
