### ISSUE TITLE
app.yml setting for external editor port

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#104]
It doesn't look like there's an option to define the port that levure will listen to when calling levureLoadExternalEditorServer

Granted you can call it with a port number (but I had to do a bit of reading to discover that).  The wiki could be updated, the application.livecodescript could discuss it, or we could have an option right in app.yml to configure it.

The bonus of the last one is that there wouldn't be the need to uncomment the levureLoadExternalEditorServer call in app.livecodescript, then, either.

**Comment by macMikey** [comment]
Workaround:
Create a .env file inside the app folder
contents of the file:
```
EXTERNAL_EDITOR_PORT=<port number>

```
Note that if you don't include the CR after the end of the line, levure will throw an error because the read file routine won't see the eof.

**Comment by trevordevore** [comment]
I've added a description of using `.env` to the docs.
