### ISSUE TITLE
preferences error windoze

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#105]
On the mac side when opening my project everything is fine.
On Windoze, I get an error loading preferences.  No preference file is specified on either platform.
<img width="414" alt="screen shot 2018-10-04 at 11 26 41" src="https://user-images.githubusercontent.com/10867016/46484808-809d9e00-c7c8-11e8-82e9-5707b617d2d3.png">

**Comment by macMikey** [comment]
FYI, the top of that message is thrown my my error handler that's intercepting errorDialog.  The bottom is the actual error message.

**Comment by trevordevore** [comment]
@macMikey After confirming that you are using the latest version of the framework can you put a breakpoint in `prefFilenameForPlatform()` in the ./framework/helpers/preferences/preferences.livecodescript file and provide the backtrace?

**Comment by trevordevore** [comment]
@macMikey Can you confirm whether or not you still see this issue? If not I'm going to close it.
