### ISSUE TITLE
helper isn't getting libraryStack message

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#107]
In the wiki there seems to be a discussion about having the libraryStack handler in a helper do stuff.  Even though my helper seems to be loaded (the backscript fires, and the stack appears in the PB, the libraryStack handler does not fire when the app loads, and it does not appear in the stacksInUse.

**Comment by trevordevore** [comment]
"helper" is a vague term in this particular case. A helper is made up of different resources and isn't a stack unto itself that is loaded. Do you have a library stack defined in the helper.yml and that stack isn't getting the libraryStack message?

**Comment by macMikey** [comment]
It didn't occur to me that I had to do that.  The goal was simply to get variables initialized for the helper to use when it fired.  I suppose I can just check the status of those variables when the helper fires and if necessary initialize them.

**Comment by trevordevore** [comment]
What do you mean by "when the helper fires"? There is no helper in the sense of messages that are sent. There are stacks within a helper that can be sent messages but there is no "helper" stack that receives messages.

**Comment by macMikey** [comment]
What I meant was when the helper is invoked.
