### ISSUE TITLE
Properly Loading Levure Project Instructions Suggestion

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#12]
I think in the standalone.livecodes page (https://github.com/trevordevore/levure/wiki/standalone.livecode), you should tell the developer that when they're working on their Levure project, they open the standalone.livecode stack.  If they don't then Levure does not get initialized and set up.  For example, if the developer opens one of the ui stack files, Levure never starts.

**Comment by trevordevore** [comment]
I've added some additional notes. Take a look and let me know if they help.

**Comment by macMikey** [comment]
Yes, that's better.
