### ISSUE TITLE
Modify levureAppGet to pull subkey values

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#120]
```levureAppHasProperty``` checks to see if subkeys exist.  Should ```levureAppGet``` do the same thing, or should we 
```
put levureAppGet("key") into keyArray
if leureAppHasProperty ("key","subkey") then put keyArray["subkey"] into goop
```

**Comment by trevordevore** [comment]
How about this?

https://github.com/trevordevore/levure/pull/122

**Comment by macMikey** [comment]
Me likey, but it literally just occurred to me as I was reading this:
the quoted parameter list or array building is a little awkward/long.  What about using colons as a substitute for dot notation since colons in a YAML file are reserved?
``` levureAppGet("key:subkey")```

**Comment by macMikey** [comment]
I'd vote ```>```.  It sticks out more when reading.

**Comment by trevordevore** [comment]
👍

**Comment by macMikey** [comment]
After sleeping on it, maybe ```,``` would be better still because it isn't _another_ new symbol for someone to have to remember to use as a separator.

**Comment by trevordevore** [comment]
I don't like the idea of using `,` for the separator. It represents `items` which is not what we are representing here.

**Comment by macMikey** [comment]
I'm ok with ```>```.  Comma would just mean one less thing to have to remember.  I don't use commas for much of anything (The data we're pulling is always from a DB so it's tsv format)

**Comment by macMikey** [comment]
So we're dumping the n-parameter model for the ```>``` model, right?  I'm working through the logger issues.

**Comment by trevordevore** [comment]
Yes. The n-parameter model has never actually been released. It was only part of this PR earlier on.
