### ISSUE TITLE
Break YAML code into its own library

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#121]
This functionality isn't Levure specific.  A couple of months ago on one of the lists someone was asking about a YAML library.  Most of the YAML code could be pulled and then put in a library that could then be submoduled.  Things like checking whether properties or keys exist and grabbing their values would then be independent of the implementation in levure.

**Comment by trevordevore** [comment]
Given that this is about extracting code from Levure for someone else to use I'm going to close this. 

The YAML library isn't used for checking for property existence, it only loads the YAML into an array.
