### ISSUE TITLE
levureAppGet ("key>subkey") doesn't

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#128]
levureAppGet accepts key>subkey, but in line 841 it returns sappa[pprop] which omits the key, i.e. it is saying return sappa[subkey] instead of sappa[key][subkey]

**Comment by trevordevore** [comment]
key>subkey is converted to an index lookup array (see tIndexA). It will be returned on line 836.

**Comment by macMikey** [comment]
Change line 834 to
``` if the number of elements of tIndexA >= 1 ```

**Comment by macMikey** [comment]
What's happening is that for single level subkeys, levure isn't obtaining the subkey value.  It works for nested subkeys 0 or >=2 levels deep.  Adding ```>=1``` fixes it.

**Comment by macMikey** [comment]
See PR 129

**Comment by trevordevore** [comment]
Got it. Thanks!
