### ISSUE TITLE
sortHelpersBasedOnDependencies Goes Into Infinite Loop

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#134]
When ```sortHelpersBasedOnDependencies``` encounters "fileBrowser" in my project with its dependency "DataView Tree" it goes into an infinite loop of sticking the helper on the end of tIndexesToProcess because "DataView Tree" is not in ```tLoadedHelpersA```

**Comment by trevordevore** [comment]
Fixed in develop: https://github.com/trevordevore/levure/commit/e78c5e0b9e33a64d4096049de0ab9aeed85e7d8f

**Comment by trevordevore** [comment]
Check that you gave the latest version of the Data View Tree and Data View installed. I had to add ‘name:’ properties to them so that they could be listed as dependencies.

**Comment by macMikey** [comment]
It looks like I have the latest of both, but DVT does not have a "name" property in the ```helper.yml``` file

**Comment by macMikey** [comment]
Boom.  Now it works.  Thanks.
