### ISSUE TITLE
logger types not being set from app.yml

### ISSUE THREAD

**Issue by bhall2001** [trevordevore/levure#137]
logger types are not with the configuration from app.yml if present. With the wiki Logger app.yml example for defining logger types, I create a new Levure app. Edit app.yml to include the Logger helper. Add the configuration from the Wiki. Config of interest being:
logger:
   types: developer,error,timer #in this case "timer" is a custom type

Open the new app via the standard Levure method. Open project browser to confirm the Levure and the Logger helper are loaded. Open message box and type put loggerGetTypes().
expected results: developer,error,timer
observed results: 

The result is empty.

NOTE: PR coming to fix that fixes this issue.

**Comment by trevordevore** [comment]
Closed by #138
