### ISSUE TITLE
Logger monitor ignores previously set types.

### ISSUE THREAD

**Issue by bhall2001** [trevordevore/levure#141]
The preOpenCard of logger_monitor.livecodescript sets the logger types. This overrides the current logger types that have been set before opening the logger_monitor (including those set from app.yml).

I personally would like to see the logger types be what they are when the logger monitor opens. There should be a check to see if the logger types are defined and if they are not, then set to the types defined in preOpenCard.

**Comment by trevordevore** [comment]
@bhall2001 I agree. With the new initialization of types when the logger loads up the monitor should just use whatever is currently set. 

In the future it would be good if the monitor had an interface for toggling all types on or off through the UI.
