### ISSUE TITLE
Creating New Project Casues LevureStandalone Stack To Take Project Name

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#144]
This is using commit 8c08149a017b2b6d64f0930e47d87bc5de7bb8b4 (latest Develop)
1. Create a new Levure project and give it a name
2. Open the standalone.livecode stack
3. Note that the name of the levureStandalone stack is the project name, not LevureStandalone.
4. Create a UI stack with the same name as your project
5. Update app.livecodescript to load that stack
6. Hit the button in LevureStandalone
You will either get an error that says that the levure framework is busy and locked or nothing will happen as the levureStandalone stack reloads itself.

**Comment by trevordevore** [comment]
@macMikey If I understand correctly you are seeing problems because you have two stacks with the same name in memory. Is that correct? What would you have Levure try to do about that?

**Comment by macMikey** [comment]
This seems to be a change of behavior, and since I didn't see it documented, I assumed it was a bug (hopefully not one I created).  If after a project is created the previously-named ```LevureStandalone``` stack is going to take on the name of the project, then I think it should be documented prominently, and there should probably be a warning about it so the developer, when building their UI stacks, doesn't use the project name for their primary stack name.

**Comment by macMikey** [comment]
It's been three years, and this has not been hitting me.
Closing.
