### ISSUE TITLE
updating old levure project - on launch SQLYoga throwing exception

### ISSUE THREAD

**Issue by rodneytamblyn** [trevordevore/levure#155]
Hi Trevor,

Hello from NZ.

In my (copious...) spare time I'm having a bit of a play with Livecode and updating an old (ie 2019) Levure-based project.  I've used git to pull down latest updates to Levure:
![image](https://user-images.githubusercontent.com/1562956/99865908-ea2fcf00-2c11-11eb-8657-0416225c1cbc.png)

When I launch my Livecode app via the Levure Application launch button I get an exception in SQLYoga.  Any idea what's going on here?
![image](https://user-images.githubusercontent.com/1562956/99865884-b8b70380-2c11-11eb-93c1-c815bd877160.png)

If there's a more appropriate place to ask questions like this let me know and I will use in future ;)

Thanks

~ Rodney

**Comment by rodneytamblyn** [comment]
I started a new project from scratch, so seems to be working.  Feel free to close.

**Comment by trevordevore** [comment]
HI @rodneytamblyn ! Glad it is working for you now. In the future, there is a SQL-yoga repo where you can submit issues. 

https://github.com/trevordevore/sql-yoga

Also, in this particular case it would be necessary to post the value of `theError` variable. That will provide a clue as to what went wrong.
