### ISSUE TITLE
question about Helpers folder

### ISSUE THREAD

**Issue by rodneytamblyn** [trevordevore/levure#156]
Hi Trevor,

There's a helper folder in the Levure/framework/helpers and also in app/helpers.    If I am using a particular helper, is it OK just to have it in the Levure helpers folder, or should I always put any/all helpers I am using in the App's helper folder?  I'm guessing that perhaps only by placing in the latter (?) would the helper be packaged when building app?

~ Rodney

**Comment by rodneytamblyn** [comment]
OK this is determined by param in yaml settings e.g.  filename: "[[FRAMEWORK]]/helpers/file_system"

**Comment by trevordevore** [comment]
@rodneytamblyn you found the right syntax. The rule is if a helper is included with Levure then leave it where it is. Any helpers you add go in your app helpers folder.
