### ISSUE TITLE
file_system helper - confirming files_and_urls ?

### ISSUE THREAD

**Issue by rodneytamblyn** [trevordevore/levure#158]
Hi Trevor,

Re: https://github.com/trevordevore/levure/wiki/helper-file_system

```
helpers:
  - folder: ./helpers
  - filename: "[[FRAMEWORK]]/helpers/files_and_urls"

```

Just confirming that the helper stack name is "file_system" but for inclusion in app.yaml I should use "helpers/files_and_urls".  

Just curious why this name is different than the helper stack name?

~ Rodney

**Comment by trevordevore** [comment]
@rodneytamblyn That example is wrong. It should be `"[[FRAMEWORK]]/helpers/files_system"`. I've updated the wiki page.
