### ISSUE TITLE
Add error checking to normalizeAppArray

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#16]
If the devloper has a badly formatted app.yml file (like the one we encountered with the applicationDataFolder path), throw an error.

**Comment by macMikey** [comment]
COROLLARY:
Build stack to build app.yml file.  You could save the settings in the stack, or if you wanted an SOS, you could save the settings in some other format that would be harder for the user to fubar.  That kind-of defeats the purpose of yml, but as long as the format of the app.yml file is changing, we probably need to add something to make legacy app.yml files forward-compatible.

**Comment by trevordevore** [comment]
Regarding Corollary - I don't think we don't need to worry about forward-compatibility yet. Until Levure hits 1.0 everything is subject to change. Changes to the app.yml file format take less than a minute to make so I don't think it is worth writing code to deal with.

**Comment by macMikey** [comment]
And here I thought since the "release" tag was out that we were working on v. 1.000000000000000000000000000001.  Instead it's 0.00000000000000000000b? Lol.

**Comment by trevordevore** [comment]
Hmm, I need to fix that tag. That shouldn't be there.

**Comment by trevordevore** [comment]
I've deleted the "release" tag :-) Going forward I will be using tags like vx.x.x. Once I tag the first release (which will be something like v0.3.0) then we will move to adding changes to a `develop` branch which will then be merged into `master`.
