### ISSUE TITLE
file_system helper - Can't get URL protocol support working

### ISSUE THREAD

**Issue by rodneytamblyn** [trevordevore/levure#161]
Hi Trevor,
I'm trying to get URL protocols working.  Following instructions on file_system helper wiki page.  
- updated my app.livecode script to include required handlers for URL protocols
- generate test standalone
- edit Info.plist to include
```
<array>
  <dict>
    <key>CFBundleURLName</key>
    <string>b4t</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>b4t</string>
    </array>
  </dict>
</array>
```
- create a test URL and email it to myself, then try following it (b4t://test_data)
- application does not launch, or if open, does not seem to receive event
- if I attempt to duplicate my standalone app, it reports that it may be damaged (probably because it is failing checksum test as the plist has been altered?)

Any ideas of things I can try?

~ Rodney

**Comment by trevordevore** [comment]
@rodneytamblyn For the Info.plist file I create my own that is built into the standalone. I store the Info.plist file in the `./app` folder. In the Standalone Application Settings > Mac tab I select the *Select a PLIST file to import into the application bundle* option and select the above Info.plist file. This should store a relative path to Info.plist that will be used when building the standalone.

Give that a try and let me know how it goes.

**Comment by rodneytamblyn** [comment]
Yes, this is likely to be the solution.  I suspect OSX will no longer allow you to “mess around” with an App’s content after it has been built.  Will test this out after the weekend and let you know how I get on :-)

~ Rodney

**Comment by trevordevore** [comment]
@rodneytamblyn I'm going to close this issue. If you think it needs to be reopened let me know.
