### ISSUE TITLE
levureTestApplicationInSimulator does not do anything?

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#166]
I have an app that I'm trying to test on ios
`levureTestApplicationInSimulator "ios", "release"` and
`levureTestApplicationInSimulator "ios"`
don't seem to do anything, and I don't get any messages.

**Comment by trevordevore** [comment]
Can you try setting a debugger in the library and see what is going on?

**Comment by macMikey** [comment]
Well, for starters,
one of the helpers (mikeys-error-handler) was assigned the packager for some reason
stay tuned for more
