### ISSUE TITLE
update *encrypt stacks* setting (or docs)

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#167]
The **encrypt stacks** setting is set to **false** when a project is created.
However [the wiki](https://github.com/trevordevore/levure/wiki/app.yml#encrypt-stacks) says that the setting should be **random**, **password** (which is a label in a `.env` file) or blank.
So either, the wiki should be updated to note that **false** is the same as blank, or the default app.yml file should be set to make it empty.

**Comment by trevordevore** [comment]
The default value should be empty so the default `app.yml` file needs updating.

**Comment by macMikey** [comment]
PR 171
