### ISSUE TITLE
Clarify app.livecodescript stages

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#18]
A little more specificity would be good.  For example, for ```InitializeApplication``` "Framework has loaded at this point", I assume, also means that my app.yml file has been processed, and front/back/library scripts are in the message path?

**Comment by macMikey** [comment]
I see that The Documentation Dood is adding some clarification.  This wiki is getting thick!

**Comment by trevordevore** [comment]
Some additional notes have been added.
