### ISSUE TITLE
Question: Is it possible to specify Privacy and Security entitlement requirements as part of build?

### ISSUE THREAD

**Issue by rodneytamblyn** [trevordevore/levure#190]
Hi Trevor,

I have an app that requires Privacy and Security permission (OSX) to access Calendar.  There's no way to manually add an app to the Calendar security pane.  Is there a way to specify permission requirements (Full Disk access, Calendar) etc as part of build process, e.g. via plist?  Or if you have any other tips or suggestions on this topic would be most interested.  In my case Livecode is not prompting for Calendar permission (although it does for Automation privilege), and thereafter script is failing.  However other users report it does add for them (https://forums.livecode.com/viewtopic.php?f=8&t=37401)

Rod

**Comment by rodneytamblyn** [comment]
I think I need to add entitlement, testing:
```
    <key>com.apple.security.personal-information.calendars</key>
    <true/>
```
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_personal-information_calendars

**Comment by rodneytamblyn** [comment]
This was the solution :-)

**Comment by trevordevore** [comment]
I'm glad you found the solution @rodneytamblyn. For anyone else who comes across this, an entitlement is just a file that you will include in your build. In the Levure `app.yml` file you would have an entry similar to the following that would add the entitlements to your resources folder.

```
build profiles:
  all profiles:
    copy files:
      macos resources:
        - filename: ../build files/Entitlements/MyApp.entitlements
```

In the code I have in my project I've named the file the same name as my app name in the Info.plist file. `../build files` is the folder that sits alongside the Levure `app` folder and contains files used when packaging the app and building installers. The file ends up in the macOS `.app/Contents/Resources` folder.

**Comment by macMikey** [comment]
do you mind if i update the wiki?

**Comment by trevordevore** [comment]
I would love it if you did @macMikey !

**Comment by macMikey** [comment]
turns out, it's already [here](https://github.com/trevordevore/levure/wiki/packager#entitlements-for-mac-app-store-or-notarized-macos-apps)

**Comment by trevordevore** [comment]
Well that was easy :-)
