### ISSUE TITLE
Disappearing Windows

### ISSUE THREAD

**Issue by martyknapp** [trevordevore/levure#205]
I recently upgraded my Mac from Monterey to Ventura and have noticed an odd behavior. It happens in the IDE and in standalones WHILE I have any open window from any other app -  if I click on a stack window to bring it to the front, it flashes to the front and then disappears back behind everything (though still open). Yet the menubar will show that I'm still in my app (or the IDE). But if I click the title bar of a stack to bring it to the front it behaves as it should. 

In the IDE this only happens after Levure has loaded - even with stacks that have no code whatsoever. If I quit and restart Livecode it functions normally. This is totally repeatable and I've tested on two Macs - an M1 Mac Mini and an Intel-based iMac. If I open the same Levure-built standalone on a previous OS it functions normally.

Anybody else seeing this? An clue as to the issue?

Stumped,
Marty

**Comment by martyknapp** [comment]
Thanks to Mark Waddingham - I tracked down the issue to "raiseWindows" being set to true. Apparently it's not playing nice with the Ventura OS

**Comment by trevordevore** [comment]
Do you set raiseWindows in your app code? I don’t think Levure ever changes that setting.

**Comment by martyknapp** [comment]
Yes, I’d forgotten that I’d done that and had to actually look.
---
Marty Knapp

**Comment by trevordevore** [comment]
I'm glad you found the solution. I'll go ahead and close this issue.
