### ISSUE TITLE
App Updater on Apple "M" Chip

### ISSUE THREAD

**Issue by martyknapp** [trevordevore/levure#206]
If I build an app (FAT) for the "M" chip Macs the app updater helper will not load. If I set the app to open using Rosetta it opens fine. Does anyone know if we can just replace "Sparkle.framework" with the latest version from Sparkle? 
<img width="792" alt="Error-FAT" src="https://user-images.githubusercontent.com/131814607/234466806-357a5a73-4b11-4e99-849a-37b953facb70.png">

**Comment by martyknapp** [comment]
I just replaced the "Sparkle.framework" folder with the latest version from the Sparkle website (2.4.1) and it now loads and seems to work OK. Just a little nervous about it though!

**Comment by trevordevore** [comment]
@martyknapp The app updater repo is located at https://github.com/trevordevore/levurehelper-app_updater. Will you log your report there?

[This commit](https://github.com/trevordevore/levurehelper-app_updater/commit/9d8734adfd20ae0cfe27f15ac1ed2ca4d232d4e5) shows what was done to update to Sparkle 1.23.0. It looks like I just replaced the Sparkle.framework file and updated the README.
