### ISSUE TITLE
Packager error with preferences helper

### ISSUE THREAD

**Issue by spencerlearning** [trevordevore/levure#29]
I am starting to use the packager and immediately ran into a problem. It appears the packager cannot handle the preferences framework helper the way it is currently set up in master. This was only tried on OS X (I am running LC 8.3 on OS X 10.9.5):

1. Follow the wiki instructions to [create a new project from master](https://github.com/trevordevore/levure/wiki/Set-Up-Your-Project-Folder).

2. Open `standalone.livecode` in a new instance of Livecode.

3. In Standalone Application Settings accept defaults except uncheck Windows and Linux so we are only building for Mac.

4. In message box, run `levurePackageApplication "beta"`. The distribution is built as expected.

5. Go to the standalone in the `builds` folder and run it.

6. An error dialog pops up: "An error occurred while initializing the application [unable to load external Preferences]."

7. This happens whether "Search for required inclusions" or "Select inclusions" is selected in the standalone settings.

Now make these changes:

1. Remove this from `app.yml`:

```
  2:
    filename: {{FRAMEWORK}}/helpers/preferences
```

2. Comment out this in `app.livecodescript`:

```
  -- if appGetPref("software build") is empty then
  --   FirstRun
  --   appSetPref "software build", levureAppGet("build")
  -- end if
```

Now rebuild and it works. The packager fails with the preferences helper. I haven't tried any other framework helpers. I also haven't tried it on Windows yet.

**Comment by trevordevore** [comment]
Pull the latest. I fixed this earlier this week but had not pushed changes.
