### ISSUE TITLE
function levureTestingStandaloneAppFolder in levure.livecodescript not defined

### ISSUE THREAD

**Issue by spencerlearning** [trevordevore/levure#3]
Function levureTestingStandaloneAppFolder in levureLoadAppConfig is not defined. It seems like it could be removed, as shown here:
https://github.com/spencerlearning/levure/commit/c0f89b3ad90e1d354913b2e1801e7aa38dd1a465

**Comment by trevordevore** [comment]
@spencerlearning `levureTestingStandaloneAppFolder` is part of a script that is added to the standalone stack when building a standalone for testing. See the `_generateStartupScript` handler in `packager.livecodescript`.
