### ISSUE TITLE
Packager build error for Windows

### ISSUE THREAD

**Issue by spencerlearning** [trevordevore/levure#30]
I tried to build for Windows with the packager and it failed to complete the build and gave an error: "can't rename file".

1. Follow the wiki instructions to [create a new project from master](https://github.com/trevordevore/levure/wiki/Set-Up-Your-Project-Folder).

2. Open `standalone.livecode` in a new instance of Livecode.

3. In Standalone Application Settings accept defaults except uncheck Mac and Linux so we are only building for Windows.

4. In message box, run `levurePackageApplication "beta"`. The build fails to complete and gives the error: "can't rename file".

Just for kicks, this was tried with and without preferences framework helper and it made no difference.

**Comment by trevordevore** [comment]
Fixed in commit 5c5aeda14c53bb4b66fe23ec1c4af6d4df0e7b17
