### ISSUE TITLE
app.yml page in the wiki does not appear to be current

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#33]
For example, the application data folder key is not the way it is shown in the app.yml folder.

As an aside, it might be nice if there were defaults included or at least discussed for some of these.  For example, if the user does not specify an application data folder for a platform, why not set it to the application data folder root for that platform + the name of the app?

e.g. I'm working on an app called "timeserver"
If I don't specify an application data folder, then on a Mac, the path could be, by default,
~/Library/Application Support/timeserver

**Comment by trevordevore** [comment]
Thanks for the heads up. I've updated the `app.yml` page with the correct syntax.

Perhaps @spencerlearning can add some examples?

Regarding automatic handling of the folder name - we could probably come up with a reasonable approach to this but I'm not sure I want to tackle that right now. I'm inclined to require developers to explicitly state where they want their application files stored for the time being.

**Comment by macMikey** [comment]
One thing on the new wiki entry - relative path for default - are slashes on front or back good or bad?  I'm assuming bad, but it isn't spelled out.

**Comment by trevordevore** [comment]
Internally the framework normalizes paths so that there are no leading slashes.

**Comment by macMikey** [comment]
See second comment - the second line of the comment lines up with the ```macos``` key - it should probably be above it

**Comment by macMikey** [comment]
ok, but what about a trailing slash?

**Comment by trevordevore** [comment]
Sorry, meant to say "trailing slashes" are stripped off. If you put a leading slash on then you are referencing the root of the volume. You don't want to do that :-)
