### ISSUE TITLE
Add a folder spec to the helper.yml file

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#38]
I have a repo that I want to submodule.  It has a ui and an library component.  The ui part is only useful if the app is being used by itself.  I THINK I should stick this submodule in the helpers folder, but the helper.yml file says that I have to specify filenames for each library stack.  If I could specify the library folder within the submodule in the helpers folder, that would save some typing and some lines in the helper.yml file.

**Comment by trevordevore** [comment]
@macMikey I'm not sure that what you describe is a good fit for a helper. I would suggest adding the submodule to your repo but then posting to the libraries folder within the submodule repo to the `libraries` section of the `app.yml` file.

```
libraries:
  1:
    folder: libraries
  2:
    folder: my-submodule/libraries
```

Is there any reason not to use this approach?

**Comment by macMikey** [comment]
I was trying to reduce clutter.

**Comment by trevordevore** [comment]
In that case I would suggest adding the submodule repo to your `libraries` folder and creating a another folder under `libraries` for your libraries specific to your project.

```
libraries:
  1:
    folder: libraries/my-app-libraries
  2:
    folder: libraries/my-submodule/libraries
```
