### ISSUE TITLE
Broadcaster Wiki page typos?

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#49]
https://github.com/trevordevore/levure/wiki/helper-broadcaster

This looks like a typo (pKey, pKey):
`# pKey is the preference key that was modified.`
`broadcasterBroadcast "prefs", pKey, pKey`

Should be `broadcasterBroadcast <pCategory>,<pBroadcasts>,<pParamsPackageA>`

**Comment by trevordevore** [comment]
This code is actually right. The category for the broadcast is `prefs`. The preference being updated is two things in this example: 

1. It is the broadcast that listeners are interested in. What this means is that whenever the preference identified by `pKey` is updated the listener wants to know.
2. It is also the parameter that is sent to the listener. It tells the listener which preference was updated. By sending the name of the preference key as a parameter one could register a single callback for multiple preference updates. One would then use the parameter passed to the callback handler to determine the specific preference that was updated.
