### ISSUE TITLE
Broadcaster Wiki Explain Purpose

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#50]
The purpose of the broadcaster is not clear to me.  Why not just call a handler that happens to be in a group/card/stack?  Is it so multiple objects can respond to the message?

**Comment by trevordevore** [comment]
Two reasons - 

- So multiple objects can respond to the message.
- So the broadcaster doesn't need to know in advance who the listener is.

**Comment by trevordevore** [comment]
I added a description to to the broadcaster wiki page

**Comment by macMikey** [comment]
Yep, that works.
