### ISSUE TITLE
Window Manager preOpenWindow/OpenWindow Issue?

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#53]
Window Manager:
In "Messages", second sentence:
The message is sent after the window and menu have been resized, however. 

Is that right?  Those messages are sent when the user resizes an open window?

**Comment by trevordevore** [comment]
They aren't sent after the user resizes a menu but the window and menu have been resized before the messages are sent when the card opens. When you open a stack it may not be the same width/height as it was last time the stack was resized. The helper resizes the menu to fit the current card width before dispatching the messages.
