### ISSUE TITLE
Window Manager Mode?

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#54]
I don't see the window modes anywhere.  Are we referring to "editable window", "palette", etc.?  If so then what do you mean in the description of windowTopMostWindowWithModeOfCeiling?  That says the stack must be of mode pMode or lower...which means what?

**Comment by trevordevore** [comment]
Mode is a property of a window. Check out the dictionary entry.

**Comment by macMikey** [comment]
Do you mean of a stack?  Window modes are described in "go", and are not numeric.  If you mean stack modes, then it makes more sense, since those are numeric.

**Comment by trevordevore** [comment]
Yes, of a stack. I've clarified the documentation.
