### ISSUE TITLE
prefsGetPref doesn't exist?

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#57]
I tried FF'ing my levure submodule.  It seems to be up-to-date.  When I open my standalone.livecode file, I'm getting an error that prefsGetPref doesn't exist.  I tried removing the submodule and re-adding it, but the problem presists.

**Comment by trevordevore** [comment]
Did you update your `app.yml` file to use the new `"[[FRAMEWORK]]/helpers/preferences"` syntax?

**Comment by macMikey** [comment]
Crap!  I totally forgot about redoing the app.yml file.  I also still had 1:, 2:, etc. in there.  That seems to have dealt with the problem, so add this to whatever the issue report was on handling badly-formed app.yml files.

**Comment by trevordevore** [comment]
Using `1:`, `2:`, ... will still work. It's just better to use `-` as you don't have to redo the numbers if your add an item to the middle of the list.
