### ISSUE TITLE
[Docs] If building for html 5 user must set width/height of standalone.livecode stack

### ISSUE THREAD

**Issue by trevordevore** [trevordevore/levure#59]
When building an HTML 5 standalone the engine uses the size of the stack being built to determine the size of the canvas in the HTML output. Set the standalone.livecode stack height/width to the size of hour UI stacks.

**Comment by EzekTec-Inc** [comment]
You meant to say **...the size of  _your_ UI stacks** 👍

**Comment by trevordevore** [comment]
Added a note to https://github.com/trevordevore/levure/wiki/Core-Application-Files
