### ISSUE TITLE
errorDialog not handled

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#61]
I just got droppped into the debugger.

I have a custom property defined in the app.yml file (releaseDate), but loading it caused an error, but the error wasn't handled and thus we end up in the debugger.  I'll email you the screenshot, because git won't let me attach it.

**Comment by trevordevore** [comment]
Levure doesn't handle `errorDialog`. I've added an FAQ describing how Levure deals with unexpected errors. 

https://github.com/trevordevore/levure/wiki/Levure-FAQ
