### ISSUE TITLE
Maybe "Building" is the wrong word

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#67]
"Build" can have another meaning, too, i.e. compiling/packaging/making installer scripts
For example,
https://github.com/trevordevore/levure/wiki/Testing-Your-Application
and
https://github.com/trevordevore/levure/wiki/packager

**Comment by trevordevore** [comment]
@macMikey Can you provide some more details along with suggested changes? The less guessing I have to do the better :-)

**Comment by macMikey** [comment]
Sorry, I forgot that you're not clairvoyant.
https://github.com/trevordevore/levure/wiki/Building-Your-Application is "Building Your Application".  When I think of "Building" my application, I don't usually think about "writing" (for lack of a better word) but compiling/packaging/building the installer.  In the other links I sent you, you use "building" in the context of compiling, etc.  However, in the "Building Your Application" section, you mean writing/organizing/designing/assembling-the-pieces

**Comment by spencerlearning** [comment]
I agree "Building Your Application" could be confusing. I changed it to "Constructing Your Application".
