### ISSUE TITLE
[Docs] Incorrect value shown for state while loading?

### ISSUE THREAD

**Issue by alextweedly** [trevordevore/levure#75]
in https://github.com/trevordevore/levure/wiki/Levure-API, under levureApplicationState, it says:

Description:

Returns a value of loading, running, or shutting down. These values reflect the internal state of the Levure application.

While Levure is loading application files at startup the state is running.  [ **** should this be 'loading' **** ]

When Levure has begun to shut down the application (e.g. the user quit the application) then the state is shutting down.

In all other cases the state is running.

**Comment by trevordevore** [comment]
Fixed. Thanks @alextweedly.
