### ISSUE TITLE
pBuildProfile

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#78]
On 
https://github.com/trevordevore/levure/wiki/packager
pBuildProfile is mentioned in
``` levurePackageApplication pBuildProfile ```
But I don't see any mention of what that does, other than name the build.

**Comment by macMikey** [comment]
Do you mean to refer to
https://github.com/trevordevore/levure/wiki/packager#the-build-profiles-section-in-appyml

**Comment by trevordevore** [comment]
I've updated the docs with some additional information.
