### ISSUE TITLE
Built Windows App Throws Error On Startup

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#83]
I'm having difficulty with an app that I built for windows.  On startup, I'm getting this error

241,30,1,OpenApplication

353,0,0,stack "\\.psf\Home\Google Drive\4D\Projects\MAMs\Versions\Archive\6.6\6.53 (including data files)\BISHalope/app.livecodescript"

675,535,1,OpenApplication

241,535,1,levureFinishLoadingApplication

353,0,0,stack "//.psf/Home/Google Drive/4D/Projects/MAMs/Versions/Archive/6.6/6.53 (including data files)/BISHalope/levure.livecodescript"

If I read it correctly, it's complaining about the line that goes to the first stack of my UI.  That works fine until I build the project and try to double-click on the compiled app.  The code for that line is just 
```go stack "BISHalope"```

**Comment by trevordevore** [comment]
@macMikey Just to confirm, the `BISHalope` stack made it into the distribution?

Also, when looking at the line number for errors in script only stacks you may need to look one line down from the line reported in the error. If you are looking at the script only stack script in a text editor then the first line will be something like `script "BISHalope"`. When the engine loads the script it strips that line off so all script lines are shift up.

**Comment by macMikey** [comment]
New patched packager fixes, until LC issues a fix to the core issue.

**Comment by trevordevore** [comment]
A fix for the LC engine will be in 8.1.7. The patch as already been merged.
