### ISSUE TITLE
Building On Windows Throws Error

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#84]
I just tested running a build on Windows, and got this error
```Done packaging application with error: copying folder //psf/Home/Google Drive/My LiveCode/ Kobe Suite/BISHalope/app/ui/BISHalope to C:/Users/Administrator/AppData/Local/Temp/levure-copy-files-1502219663808/ui/BISHalope ('\\psf\Home\Google Drive\My LiveCode\ Kobe Suite\BISHalope\BISHalope_files')```

**Comment by trevordevore** [comment]
Can you upload the copy files section of your app.yml file so I can take a look?

**Comment by macMikey** [comment]
It's empty, because I'm not copying anything more than the defaults
    copy files:
      all platforms:
      macos:
      windows:
      linux:
      ios:
      android:

**Comment by trevordevore** [comment]
What happens if you copy the folder with your app off of the network drive and onto a local drive and then try to build?

**Comment by macMikey** [comment]
Screenshots and such emailed to you.

**Comment by trevordevore** [comment]
@macMikey Is this still an issue you are experiencing?

**Comment by macMikey** [comment]
I haven't tried to build this app in forever, so I would just close it for now.

**Comment by trevordevore** [comment]
👍🏻
