### ISSUE TITLE
Add Sublime Text Files When Create Startup Application

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#88]
Add a checkbox to the create project stack for "Use ST as my editor".  In that case the user will be prompted for a project name, and then the .sublime-project file will be auto-created, the app.livecodescript file will have the ST lines uncommented, the folder will be named, and if you really want to get creative, the app.yml file will have the name of the project in the name line.

**Comment by macMikey** [comment]
PR 117

**Comment by macMikey** [comment]
PR 117 was accepted, right?  I think this can be closed.

**Comment by trevordevore** [comment]
Yes it was. I'll close this.
