### ISSUE TITLE
Testing new packager

### ISSUE THREAD

**Issue by trevordevore** [trevordevore/levure#89]
Over the last two months I've been updating the Levure packager. I converted a second application to Levure and it needs to be submitted to the Mac App Store. In order to support that workflow I had to add some new settings that allow you to apply build profile filters to files being packaged up (e.g. only include file x when packaging for the mac app store). I recorded a screencast about it:

https://www.youtube.com/watch?v=hnBlTtFmfoc

During this process I had to change a lot of the internals. I'm successfully packaging the original app I ported to Levure and the new app. Can anyone who has experience packaging applications replace the `levure` folder in their app with the one from the `tkd-exclude-from-build-profiles` branch and try packaging? I would be interested to know if I've broken anything for you.

https://github.com/trevordevore/levure/tree/tkd-exclude-from-build-profiles

**Comment by spencerlearning** [comment]
Using the `levure` folder from the `tkd-exclude-from-build-profiles` branch I successfully packaged my app for iOS, Android, Windows and Mac. I don't use the simulators but everything seemed to work fine on my devices.

**Comment by trevordevore** [comment]
Thanks @spencerlearning. I just released 0.9.4 with the packager changes. The release notes list all of the changes.

https://github.com/trevordevore/levure/releases
