### ISSUE TITLE
Unable to load external preferences when clicking open Application

### ISSUE THREAD

**Issue by HaraldSchlager** [trevordevore/levure#90]
hi, i want to try / use levure and on my first test I got this error message on a Mac with LC business 9 DP8. 

"An error occurred while initializing the appication [Unable to load external preferences] "

Is there any log where I can go into which preferences should be loaded ?

Thanks,
Harald

**Comment by trevordevore** [comment]
The LC 9 IDE runs as 64-bit. The preferences external was 32-bit. I just released Levure 0.9.4 which has a 64-bit version of the preferences external that @livecodemark provided. Create a new project from scratch and it should work.

**Comment by HaraldSchlager** [comment]
Thank you for the fast fix. It is working. br

**Comment by trevordevore** [comment]
You're welcome.
