### ISSUE TITLE
ui stack loaded out-of-sequence warning or correction

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#92]
As long as LC is going to list both standalone and the UI stack in the recent list, i'd like a way to recover gracefully when i open the wrong one, either by having a way to close the ui stack and open standalone, or some other way to recover easily.

**Comment by trevordevore** [comment]
This is a bit of a vague request. If you can list some more specifics and want to actually code it yourself I will leave it open :-) Otherwise I am going to close it.

**Comment by macMikey** [comment]
I'm not sure how it's vague.  You open a levure project in LC using the standalone stack.  That initializes the framework.  From there you open the UI stack(s).  However, when you do that and load the interface stack, both end up in LC's "recent" list, which means you have to read through the list of entries to make sure you open "standalone" and not the UI stack.  I don't have a good idea on how to manage this.  If I was going to do it manually, I guess in the preloadApplication or openApplication handler I would have a global set, something like "levureLoaded".  Then the ui stack would have to check to see if levureLoaded was true or not, and if it was, proceed, but if not, abort.  You can't have a straight call in the levure API, because if you've loaded the UI and not standalone, then the framework isn't loaded.  It would be better if we had some way to manually start the framework after the UI is already loaded, then proceed with whatever handler we were executing in the UI stack.

As an alternative, perhaps there is a way to override the recent open stacks list in LC so that only the standalone stack shows up, not the UI stack?

**Comment by trevordevore** [comment]
Currently you don't have to add any levure-specific logic to a ui stack which I see as a good thing. I don't see this as a significantly enough issue to warrant changing that. Also, I don't think it is place of the framework to override the recent file list in the ide.

I would categorize this type of request under some sort of IDE plugin that is separate from the actual framework.
