### ISSUE TITLE
Converting Preferences saved as a .plist file by GLX app to Levure

### ISSUE THREAD

**Issue by MartinKoob** [trevordevore/levure#99]
Hi Trevor

I have a further question about converting preferences saved by the GLX framework to Levure.

I found your script for converting GLX externals to Levure externals

https://github.com/trevordevore/levure/blob/master/utils/convert%20old%20prefs%20to%20levure%20prefs.md

However I noticed in the script that it seems to require that the preferences are stored in a stack file.  The preferences for my GLX based Mac OS X app are saved in the user preferences file as a .plist.  
The change to a .plist is due to the change you made in version 1.2.0 Build 1 to meet the requirements of Mac OS X sandboxing as you explained in this post in the GLX Google Group: https://groups.google.com/forum/#!searchin/glxapp/preferences.bundle%7Csort:date/glxapp/vTjjNpuSsS4/GKxh6LVehGwJ

Is there a need to convert preferences stored by a GLX based app as a .plist to Levure?  If so do you have a script for that, or modifications to the first script so that it can take a .plist file as an input as well?

Thanks

Martin Koob

**Comment by trevordevore** [comment]
@MartinKoob On macOS Levure uses the same preference external as GLX App so there is no conversion that needs to be made. You will only need to convert on Windows if you are using the external.
